<?php
/**
 * @author Xigen
 */
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
$postsCount = 0;
?>
<?php if ($posts = $block->getBlogPosts()) : ?>
    <div class="block widget block-posts-list">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('From the Blog')) ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-posts-<?= $block->escapeHtmlAttr($suffix) ?>" 
                class="product-items product-items-list">
                <?php foreach ($posts as $post) : ?>
                    <?php
                    $postsCount++;
                    if ($block->getPostsCount() >= $postsCount) {
                        continue;
                    }
                    ?>
                    <li class="product-item">
                        <?php if (isset($post['link'])) : ?>
                        <a class="product-item-photo" 
                           href="<?= $block->escapeUrl($post['link']); ?>"
                           target="_blank"
                           title="<?= $block->escapeHtmlAttr($post['title']['rendered']); ?>">
                        <?php endif; ?>
                        <?php if (isset($post['_embedded']['wp:featuredmedia'][0]['media_details']["sizes"]["thumbnail"])) : ?>
                            <img src="<?= /* @noEscape */ $post['_embedded']['wp:featuredmedia'][0]['media_details']["sizes"]["thumbnail"]["source_url"]; ?>" 
                                 alt="<?= $block->escapeHtmlAttr($post['title']['rendered']); ?>"
                                 title="<?= $block->escapeHtmlAttr($post['title']['rendered']); ?>" />
                        <?php endif; ?>
                        <?php if (isset($post['link'])) : ?>
                        </a>
                        <?php endif; ?>
                        <p class="blog-post-title"><?= $block->escapeHtmlAttr($post['title']['rendered']); ?></p>
                        <p class="blog-post-excerpt">
                            <?= /* @noEscape */  $block->tidyText($post['content']['rendered']); ?>
                        </p>
                        <?php if (isset($post['link'])) : ?>
                        <p class="blog-post-link">
                            <?= /* @noEscape */ __("Click <a href='%1' target='_blank'>here</a> to read more", $block->escapeUrl($post['link'])); ?>
                        </p>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
